import '../entities/call_entity.dart';
import '../entities/call_session_entity.dart';
import '../repositories/video_call_repository.dart';

/// Answer Call Use Case
/// Business logic for answering an incoming video call
class AnswerCallUseCase {
  final VideoCallRepository _repository;

  AnswerCallUseCase(this._repository);

  /// Execute the use case
  ///
  /// Parameters:
  /// - [callId]: ID of the call to answer
  /// - [sdpAnswer]: WebRTC SDP answer generated by the callee
  ///
  /// Throws: Exception if call doesn't exist or is not in ringing state
  Future<void> execute({
    required String callId,
    required SdpEntity sdpAnswer,
  }) async {
    // Validation
    if (callId.isEmpty) {
      throw ArgumentError('Call ID cannot be empty');
    }

    // Get call to verify it exists and is in correct state
    final call = await _repository.getCall(callId);

    if (call.status != CallStatus.ringing) {
      throw StateError(
          'Call is not in ringing state. Current status: ${call.status}');
    }

    // Answer the call
    await _repository.answerCall(
      callId: callId,
      sdpAnswer: sdpAnswer,
    );
  }
}
