import '../entities/call_session_entity.dart';
import '../repositories/video_call_repository.dart';

/// Initiate Call Use Case
/// Business logic for starting a new video call
class InitiateCallUseCase {
  final VideoCallRepository _repository;

  InitiateCallUseCase(this._repository);

  /// Execute the use case
  ///
  /// Parameters:
  /// - [callerId]: ID of the user initiating the call
  /// - [calleeId]: ID of the user receiving the call
  /// - [sdpOffer]: WebRTC SDP offer generated by the caller
  ///
  /// Returns: Call ID
  ///
  /// Throws: Exception if call creation fails
  Future<String> execute({
    required String callerId,
    required String calleeId,
    required SdpEntity sdpOffer,
  }) async {
    // Validation
    if (callerId.isEmpty) {
      throw ArgumentError('Caller ID cannot be empty');
    }
    if (calleeId.isEmpty) {
      throw ArgumentError('Callee ID cannot be empty');
    }
    if (callerId == calleeId) {
      throw ArgumentError('Cannot call yourself');
    }

    // Create the call
    final callId = await _repository.initiateCall(
      callerId: callerId,
      calleeId: calleeId,
      sdpOffer: sdpOffer,
    );

    return callId;
  }
}
