// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnmhW9ShSFjoYO4lBcpN-Oz4A4JEgcc6U',
    appId: '1:414558541094:web:97fbe740757940cfef1de7',
    messagingSenderId: '414558541094',
    projectId: 'flutter-messaging-app-72758',
    authDomain: 'flutter-messaging-app-72758.firebaseapp.com',
    storageBucket: 'flutter-messaging-app-72758.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJeLr6KslpdnBBB_02nvwAPgqRaTXExr4',
    appId: '1:414558541094:android:5e6cdf23187d7373ef1de7',
    messagingSenderId: '414558541094',
    projectId: 'flutter-messaging-app-72758',
    storageBucket: 'flutter-messaging-app-72758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEKjL5t0tbo-w5I6iVgoUZFIT7_aUna9s',
    appId: '1:414558541094:ios:46e38bc2211385d5ef1de7',
    messagingSenderId: '414558541094',
    projectId: 'flutter-messaging-app-72758',
    storageBucket: 'flutter-messaging-app-72758.firebasestorage.app',
    iosBundleId: 'com.example.messagingApp',
  );
}
